"""VisionBackend: what the voice tools call to use the camera.

Same contract as MotionBackend (robot_core/motion.py), for the same reason:
tool calls run inside the Live session's receive loop, so **nothing here may
block**. Every method starts the work and returns at once; the outcome arrives
later on the shared `results` queue as {"text": "..."} and is fed to the model
as context. `stop_following` is the exception — immediate, like stop().

Implemented in the ROS build by robot_voice.ros_bridge.RosVision.
"""

from __future__ import annotations

from typing import Any, Dict, Optional, Protocol


class VisionBackend(Protocol):
    def look(self) -> Dict[str, Any]: ...
    def who(self) -> Dict[str, Any]: ...
    def look_at(self, what: str) -> Dict[str, Any]: ...
    def follow(self, name: Optional[str] = None) -> Dict[str, Any]: ...
    def stop_following(self) -> Dict[str, Any]: ...
    def approach(self, what: str) -> Dict[str, Any]: ...
    def clear_path(self) -> Dict[str, Any]: ...
    def remember_face(self, name: str) -> Dict[str, Any]: ...
